// src/styles/themes.ts
// Single source of truth for all HMS color schemes.
// Each scheme defines both light and dark mode CSS variable values.
// The useThemeStore injects these into :root at runtime.

export type ThemeMode = 'light' | 'dark';

export interface ThemeVars {
  '--bg-main': string;
  '--bg-card': string;
  '--text-primary': string;
  '--text-secondary': string;
  '--text-tertiary': string;
  '--icon-cyan-bg': string;
  '--icon-cyan-text': string;
  '--icon-orange-bg': string;
  '--icon-orange-text': string;
  '--icon-red-bg': string;
  '--icon-red-text': string;
  '--icon-green-bg': string;
  '--icon-green-text': string;
  '--icon-purple-bg': string;
  '--icon-purple-text': string;
  '--icon-yellow-bg': string;
  '--icon-yellow-text': string;
  '--border-color': string;
  '--shadow-sm': string;
  '--shadow-md': string;
}

export interface ColorScheme {
  id: string;
  name: string;
  description: string;
  previewAccent: string;
  previewBg: { light: string; dark: string };
  light: ThemeVars;
  dark: ThemeVars;
}

// ─── Scheme 1: Original ──────────────────────────────────────────────────────
const originalScheme: ColorScheme = {
  id: 'original',
  name: 'Original',
  description: 'The default HMS palette — light gray base with cyan accents',
  previewAccent: '#0891b2',
  previewBg: { light: '#e5e7eb', dark: '#1f2937' },
  light: {
    '--bg-main': '#e5e7eb',
    '--bg-card': '#ffffff',
    '--text-primary': '#111827',
    '--text-secondary': '#6b7280',
    '--text-tertiary': '#9ca3af',
    '--icon-cyan-bg': '#a5f3fc',
    '--icon-cyan-text': '#0891b2',
    '--icon-orange-bg': '#fed7aa',
    '--icon-orange-text': '#ea580c',
    '--icon-red-bg': '#fecaca',
    '--icon-red-text': '#dc2626',
    '--icon-green-bg': '#bbf7d0',
    '--icon-green-text': '#16a34a',
    '--icon-purple-bg': '#e9d5ff',
    '--icon-purple-text': '#9333ea',
    '--icon-yellow-bg': '#fef08a',
    '--icon-yellow-text': '#ca8a04',
    '--border-color': '#e5e7eb',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1)',
  },
  dark: {
    '--bg-main': '#1f2937',
    '--bg-card': '#374151',
    '--text-primary': '#f9fafb',
    '--text-secondary': '#d1d5db',
    '--text-tertiary': '#9ca3af',
    '--icon-cyan-bg': '#164e63',
    '--icon-cyan-text': '#67e8f9',
    '--icon-orange-bg': '#7c2d12',
    '--icon-orange-text': '#fdba74',
    '--icon-red-bg': '#7f1d1d',
    '--icon-red-text': '#fca5a5',
    '--icon-green-bg': '#14532d',
    '--icon-green-text': '#86efac',
    '--icon-purple-bg': '#581c87',
    '--icon-purple-text': '#d8b4fe',
    '--icon-yellow-bg': '#713f12',
    '--icon-yellow-text': '#fde047',
    '--border-color': '#4b5563',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 2: Arctic Slate ──────────────────────────────────────────────────
const arcticSlate: ColorScheme = {
  id: 'arctic-slate',
  name: 'Arctic Slate',
  description: 'Cool, clean, professional — inspired by arctic ice and slate tones',
  previewAccent: '#1D4ED8',
  previewBg: { light: '#EEF2F7', dark: '#0D1521' },
  light: {
    '--bg-main': '#EEF2F7',
    '--bg-card': '#FFFFFF',
    '--text-primary': '#1B2A3D',
    '--text-secondary': '#4F6C8A',
    '--text-tertiary': '#8AAABF',
    '--icon-cyan-bg': '#DBEAFE',
    '--icon-cyan-text': '#1D4ED8',
    '--icon-orange-bg': '#FFEDD5',
    '--icon-orange-text': '#C2410C',
    '--icon-red-bg': '#FEE2E2',
    '--icon-red-text': '#B91C1C',
    '--icon-green-bg': '#D1FAE5',
    '--icon-green-text': '#065F46',
    '--icon-purple-bg': '#FCE7F3',
    '--icon-purple-text': '#9D174D',
    '--icon-yellow-bg': '#FEF3C7',
    '--icon-yellow-text': '#92400E',
    '--border-color': '#C8D6E5',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.06)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.08)',
  },
  dark: {
    '--bg-main': '#0D1521',
    '--bg-card': '#162032',
    '--text-primary': '#CBD8E8',
    '--text-secondary': '#4F7298',
    '--text-tertiary': '#2D4A66',
    '--icon-cyan-bg': '#0C2152',
    '--icon-cyan-text': '#60A5FA',
    '--icon-orange-bg': '#2D1200',
    '--icon-orange-text': '#FB923C',
    '--icon-red-bg': '#290808',
    '--icon-red-text': '#FCA5A5',
    '--icon-green-bg': '#052E16',
    '--icon-green-text': '#6EE7B7',
    '--icon-purple-bg': '#2D0A1E',
    '--icon-purple-text': '#F9A8D4',
    '--icon-yellow-bg': '#2D1F00',
    '--icon-yellow-text': '#FDE047',
    '--border-color': '#243650',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 3: Sage Clinic ───────────────────────────────────────────────────
const sageClinic: ColorScheme = {
  id: 'sage-clinic',
  name: 'Sage Clinic',
  description: 'Calming green tones — reduces eye strain for long clinical shifts',
  previewAccent: '#15803D',
  previewBg: { light: '#F0F4F1', dark: '#0C1810' },
  light: {
    '--bg-main': '#F0F4F1',
    '--bg-card': '#FFFFFF',
    '--text-primary': '#1A2E22',
    '--text-secondary': '#3D6B50',
    '--text-tertiary': '#7AA88A',
    '--icon-cyan-bg': '#DCFCE7',
    '--icon-cyan-text': '#15803D',
    '--icon-orange-bg': '#FFEDD5',
    '--icon-orange-text': '#C2410C',
    '--icon-red-bg': '#FEE2E2',
    '--icon-red-text': '#B91C1C',
    '--icon-green-bg': '#E0F2FE',
    '--icon-green-text': '#0369A1',
    '--icon-purple-bg': '#F3E8FF',
    '--icon-purple-text': '#7E22CE',
    '--icon-yellow-bg': '#FEF9C3',
    '--icon-yellow-text': '#854D0E',
    '--border-color': '#C2D5C8',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.06)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.08)',
  },
  dark: {
    '--bg-main': '#0C1810',
    '--bg-card': '#142418',
    '--text-primary': '#C4DEC9',
    '--text-secondary': '#3A7A50',
    '--text-tertiary': '#1E4A28',
    '--icon-cyan-bg': '#052E16',
    '--icon-cyan-text': '#4ADE80',
    '--icon-orange-bg': '#2D1200',
    '--icon-orange-text': '#FB923C',
    '--icon-red-bg': '#290808',
    '--icon-red-text': '#FCA5A5',
    '--icon-green-bg': '#0C2840',
    '--icon-green-text': '#7DD3FC',
    '--icon-purple-bg': '#1F0A3A',
    '--icon-purple-text': '#D8B4FE',
    '--icon-yellow-bg': '#2A1F00',
    '--icon-yellow-text': '#FDE047',
    '--border-color': '#1E3824',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 4: Violet Care (with improved dark mode) ──────────────────────────
const violetCare: ColorScheme = {
  id: 'violet-care',
  name: 'Violet Care',
  description: 'Elegant purple palette — sophisticated and modern',
  previewAccent: '#6D28D9',
  previewBg: { light: '#F5F3FF', dark: '#0F0B1A' },
  light: {
    '--bg-main': '#F5F3FF',
    '--bg-card': '#FFFFFF',
    '--text-primary': '#1E1558',
    '--text-secondary': '#5B4DB0',
    '--text-tertiary': '#9B8FD4',
    '--icon-cyan-bg': '#EDE9FE',
    '--icon-cyan-text': '#6D28D9',
    '--icon-orange-bg': '#FFEDD5',
    '--icon-orange-text': '#C2410C',
    '--icon-red-bg': '#FCE7F3',
    '--icon-red-text': '#9D174D',
    '--icon-green-bg': '#D1FAE5',
    '--icon-green-text': '#065F46',
    '--icon-purple-bg': '#EDE9FE',
    '--icon-purple-text': '#5B21B6',
    '--icon-yellow-bg': '#FEF3C7',
    '--icon-yellow-text': '#92400E',
    '--border-color': '#DDD6FE',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.06)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.08)',
  },
  dark: {
    '--bg-main': '#0F0B1A',
    '--bg-card': '#1A1438',
    '--text-primary': '#D8CEFF',
    '--text-secondary': '#8B7ED4',
    '--text-tertiary': '#5C4B9E',
    '--icon-cyan-bg': '#2D1A6E',
    '--icon-cyan-text': '#B8A6FF',
    '--icon-orange-bg': '#2D1200',
    '--icon-orange-text': '#FB923C',
    '--icon-red-bg': '#2D0A28',
    '--icon-red-text': '#F9A8D4',
    '--icon-green-bg': '#0A2E1A',
    '--icon-green-text': '#8CE6B2',
    '--icon-purple-bg': '#2D1A6E',
    '--icon-purple-text': '#C4ADFF',
    '--icon-yellow-bg': '#2D1F00',
    '--icon-yellow-text': '#FDE047',
    '--border-color': '#2D2660',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.35)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.45)',
  },
};

// ─── Scheme 5: Obsidian Gold ─────────────────────────────────────────────────
const obsidianGold: ColorScheme = {
  id: 'obsidian-gold',
  name: 'Obsidian Gold',
  description: 'Premium earthy tones — elegant and distinctive',
  previewAccent: '#B45309',
  previewBg: { light: '#F7F6F2', dark: '#100F08' },
  light: {
    '--bg-main': '#F7F6F2',
    '--bg-card': '#FFFFFF',
    '--text-primary': '#1C1A10',
    '--text-secondary': '#6B6340',
    '--text-tertiary': '#A89D70',
    '--icon-cyan-bg': '#FEF3C7',
    '--icon-cyan-text': '#B45309',
    '--icon-orange-bg': '#FFEDD5',
    '--icon-orange-text': '#C2410C',
    '--icon-red-bg': '#FEE2E2',
    '--icon-red-text': '#B91C1C',
    '--icon-green-bg': '#D1FAE5',
    '--icon-green-text': '#065F46',
    '--icon-purple-bg': '#EDE9FE',
    '--icon-purple-text': '#6D28D9',
    '--icon-yellow-bg': '#DBEAFE',
    '--icon-yellow-text': '#1D4ED8',
    '--border-color': '#DDD9C8',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.06)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.08)',
  },
  dark: {
    '--bg-main': '#100F08',
    '--bg-card': '#1E1C0E',
    '--text-primary': '#EDE9D4',
    '--text-secondary': '#8A7A38',
    '--text-tertiary': '#4A4218',
    '--icon-cyan-bg': '#2D2000',
    '--icon-cyan-text': '#FBBF24',
    '--icon-orange-bg': '#2D1200',
    '--icon-orange-text': '#FB923C',
    '--icon-red-bg': '#290808',
    '--icon-red-text': '#FCA5A5',
    '--icon-green-bg': '#052E16',
    '--icon-green-text': '#6EE7B7',
    '--icon-purple-bg': '#1A0A3A',
    '--icon-purple-text': '#C4B5FD',
    '--icon-yellow-bg': '#0C2152',
    '--icon-yellow-text': '#60A5FA',
    '--border-color': '#332E10',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 6: Slate & Indigo (with improved dark mode) ───────────────────────
const slateIndigo: ColorScheme = {
  id: 'slate-indigo',
  name: 'Slate & Indigo',
  description: 'Sophisticated, data-dense, sharp — great for power users',
  previewAccent: '#4f46e5',
  previewBg: { light: '#f1f2f6', dark: '#0a0a14' },
  light: {
    '--bg-main': '#f1f2f6',
    '--bg-card': '#ffffff',
    '--text-primary': '#1e1f3b',
    '--text-secondary': '#555880',
    '--text-tertiary': '#8285b0',
    '--icon-cyan-bg': '#ede9fe',
    '--icon-cyan-text': '#4338ca',
    '--icon-orange-bg': '#ffedd5',
    '--icon-orange-text': '#c2410c',
    '--icon-red-bg': '#fee2e2',
    '--icon-red-text': '#991b1b',
    '--icon-green-bg': '#d1fae5',
    '--icon-green-text': '#065f46',
    '--icon-purple-bg': '#ede9fe',
    '--icon-purple-text': '#5b21b6',
    '--icon-yellow-bg': '#fef3c7',
    '--icon-yellow-text': '#92400e',
    '--border-color': '#d4d5e0',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1)',
  },
  dark: {
    '--bg-main': '#0A0A14',
    '--bg-card': '#151628',
    '--text-primary': '#E2E4FF',
    '--text-secondary': '#8B8ED4',
    '--text-tertiary': '#525494',
    '--icon-cyan-bg': '#2D2A6E',
    '--icon-cyan-text': '#A5B4FC',
    '--icon-orange-bg': '#2D1200',
    '--icon-orange-text': '#FB923C',
    '--icon-red-bg': '#2D0A0A',
    '--icon-red-text': '#FCA5A5',
    '--icon-green-bg': '#0A2E1A',
    '--icon-green-text': '#86EFAC',
    '--icon-purple-bg': '#2D1A6E',
    '--icon-purple-text': '#C4B5FD',
    '--icon-yellow-bg': '#2D1F00',
    '--icon-yellow-text': '#FDE047',
    '--border-color': '#252642',
    '--shadow-sm': '0 1px 3px rgba(0,0,0,0.4)',
    '--shadow-md': '0 4px 12px rgba(0,0,0,0.5)',
  },
};

// ─── Scheme 7: Teal & Ivory (kept for variety) ───────────────────────────────
const tealIvory: ColorScheme = {
  id: 'teal-ivory',
  name: 'Teal & Ivory',
  description: 'Calm, wellness-forward, modern — great for daily use',
  previewAccent: '#0d9488',
  previewBg: { light: '#f2f7f5', dark: '#0f1f1d' },
  light: {
    '--bg-main': '#f2f7f5',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a3330',
    '--text-secondary': '#3d6b5e',
    '--text-tertiary': '#6a9688',
    '--icon-cyan-bg': '#ccfbf1',
    '--icon-cyan-text': '#0f766e',
    '--icon-orange-bg': '#ffedd5',
    '--icon-orange-text': '#c2410c',
    '--icon-red-bg': '#fee2e2',
    '--icon-red-text': '#b91c1c',
    '--icon-green-bg': '#dcfce7',
    '--icon-green-text': '#15803d',
    '--icon-purple-bg': '#f3e8ff',
    '--icon-purple-text': '#7e22ce',
    '--icon-yellow-bg': '#fef9c3',
    '--icon-yellow-text': '#854d0e',
    '--border-color': '#c8ddd8',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1)',
  },
  dark: {
    '--bg-main': '#0c1c18',
    '--bg-card': '#1a302c',
    '--text-primary': '#e0f2ef',
    '--text-secondary': '#4db8ae',
    '--text-tertiary': '#2a7a70',
    '--icon-cyan-bg': '#042f2e',
    '--icon-cyan-text': '#5eead4',
    '--icon-orange-bg': '#2d1000',
    '--icon-orange-text': '#fb923c',
    '--icon-red-bg': '#200808',
    '--icon-red-text': '#fca5a5',
    '--icon-green-bg': '#052e16',
    '--icon-green-text': '#86efac',
    '--icon-purple-bg': '#1f0a3a',
    '--icon-purple-text': '#d8b4fe',
    '--icon-yellow-bg': '#2d1f00',
    '--icon-yellow-text': '#fde047',
    '--border-color': '#1e3a35',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 8: Warm Neutral (kept for variety) ────────────────────────────────
const warmNeutral: ColorScheme = {
  id: 'warm-neutral',
  name: 'Warm Neutral',
  description: 'Human-centered, stone tones — reduces eye strain for long shifts',
  previewAccent: '#0ea5e9',
  previewBg: { light: '#f5f3f0', dark: '#1c1917' },
  light: {
    '--bg-main': '#f5f3f0',
    '--bg-card': '#ffffff',
    '--text-primary': '#1c1917',
    '--text-secondary': '#57534e',
    '--text-tertiary': '#a8a29e',
    '--icon-cyan-bg': '#e0f2fe',
    '--icon-cyan-text': '#0284c7',
    '--icon-orange-bg': '#ffedd5',
    '--icon-orange-text': '#c2410c',
    '--icon-red-bg': '#fee2e2',
    '--icon-red-text': '#b91c1c',
    '--icon-green-bg': '#dcfce7',
    '--icon-green-text': '#166534',
    '--icon-purple-bg': '#f3e8ff',
    '--icon-purple-text': '#7e22ce',
    '--icon-yellow-bg': '#fef3c7',
    '--icon-yellow-text': '#92400e',
    '--border-color': '#d6d0c8',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1)',
  },
  dark: {
    '--bg-main': '#1c1917',
    '--bg-card': '#292524',
    '--text-primary': '#f5f3f0',
    '--text-secondary': '#a8a29e',
    '--text-tertiary': '#78716c',
    '--icon-cyan-bg': '#0c2840',
    '--icon-cyan-text': '#7dd3fc',
    '--icon-orange-bg': '#2a1200',
    '--icon-orange-text': '#fdba74',
    '--icon-red-bg': '#250808',
    '--icon-red-text': '#fca5a5',
    '--icon-green-bg': '#052e16',
    '--icon-green-text': '#86efac',
    '--icon-purple-bg': '#1f0a38',
    '--icon-purple-text': '#d8b4fe',
    '--icon-yellow-bg': '#2d1c00',
    '--icon-yellow-text': '#fde047',
    '--border-color': '#3d3835',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.4)',
  },
};

// ─── Scheme 9: Clinical Blue (kept for variety) ───────────────────────────────
const clinicalBlue: ColorScheme = {
  id: 'clinical-blue',
  name: 'Clinical Blue',
  description: 'Trustworthy hospital-grade navy and blue tones',
  previewAccent: '#0066cc',
  previewBg: { light: '#f0f4f8', dark: '#0d1b2a' },
  light: {
    '--bg-main': '#f0f4f8',
    '--bg-card': '#ffffff',
    '--text-primary': '#1a2e44',
    '--text-secondary': '#4a6080',
    '--text-tertiary': '#7a90a8',
    '--icon-cyan-bg': '#e8f4ff',
    '--icon-cyan-text': '#0052a3',
    '--icon-orange-bg': '#fff0e6',
    '--icon-orange-text': '#c2500a',
    '--icon-red-bg': '#fde8e8',
    '--icon-red-text': '#c53030',
    '--icon-green-bg': '#d4edda',
    '--icon-green-text': '#1a6b3a',
    '--icon-purple-bg': '#ede4f8',
    '--icon-purple-text': '#6b21a8',
    '--icon-yellow-bg': '#fef9c3',
    '--icon-yellow-text': '#856404',
    '--border-color': '#d0dae6',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.1)',
  },
  dark: {
    '--bg-main': '#0d1b2a',
    '--bg-card': '#14263a',
    '--text-primary': '#e2eaf4',
    '--text-secondary': '#8aabbd',
    '--text-tertiary': '#4a6580',
    '--icon-cyan-bg': '#0a2040',
    '--icon-cyan-text': '#89cff0',
    '--icon-orange-bg': '#2a1000',
    '--icon-orange-text': '#ffaa66',
    '--icon-red-bg': '#1f0a0a',
    '--icon-red-text': '#ff9999',
    '--icon-green-bg': '#0a2818',
    '--icon-green-text': '#6dd89a',
    '--icon-purple-bg': '#1a0a40',
    '--icon-purple-text': '#c4a8ff',
    '--icon-yellow-bg': '#2a1f00',
    '--icon-yellow-text': '#ffd966',
    '--border-color': '#1e3550',
    '--shadow-sm': '0 1px 2px 0 rgba(0,0,0,0.3)',
    '--shadow-md': '0 4px 6px -1px rgba(0,0,0,0.4)',
  },
};

// ─── Exported registry ────────────────────────────────────────────────────────
export const COLOR_SCHEMES: ColorScheme[] = [
  originalScheme,
  arcticSlate,
  sageClinic,
  violetCare,
  obsidianGold,
  slateIndigo,
  tealIvory,
  warmNeutral,
  clinicalBlue,
];

export const DEFAULT_SCHEME_ID = 'original';